# -*- coding: utf-8 -*-
"""Exercises_02_Lists.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N4JLgoYi5LEY2qHBYqiBaNT6sB8L4pEU

# Exercises using lists

**NOTE: Use the commands that we have seen in class up to now.**

1. Write with a sentence if that: given a certain number, it prints its absolute value
"""

n= -5
if n<0:
  print("Absolute value of negative number", n, "is", abs(n))
else:
  print("Absolute value of positive number", n, "is", abs(n))

"""2. Create a list of 5 different numbers and use a for-in loop to print the absolute value of each element in the list."""

num = (1,2,-3,4,-5)
for index, n in enumerate(num):
  print(abs(n))

"""3. Write a program, that given three different numbers a, b, and c, and prints which is the maximum and the minimum."""

a=12
b=36
c=72

print(min(a,b,c))
print(max(a,b,c))
print(a,b,c)

"""4. Write a program in python that, given two integer numbers, print one of these messages: "The second is the square of the first number", "The second is minor than the square of the first number", "The second is greater than the square of the first number". The different messages have to printed if that condition is true."""

a=2
b=3

if b==a**2:
  print("The second is the square of the first number")
elif b<a**2:
  print("The second is minor than the square of the first number")
else:
  print("The second is greater than the square of the first number")

"""5. Write a program in Python that, given 5 different names in lower case letters, print each name in title and the classroom in which is going to do the exam according to:

- Surnames from  A to F -> Classroom 1
- Surnames from  G to M -> Classroom 2
- Surnames from  N to Z -> Classroom 3

"""

names=("juan", "eduardo", "jose", "zebra", "miguel")

for name in names:
  title_name=name.title()
  first=name.split()[-1]

  if 'a' <= first[0] <= 'f':
    print(f"{title_name} will go to classroom 1")
  elif 'g' <= first[0] <= 'm':
    print(f"{title_name} will go to classroom 2")
  else:
    print(f"{title_name} will go to classroom 3")

"""6. Write a program  that detects if there are vowels inside a string. You can consider vowels without accent marks."""

string1= ("george")
string2= ("bylt")
string3= ("sdfg")
vowels = ("aeiouAEIOU")

has= any(char in vowels for char in string1)

if has:
  print("String contains vowels")
else:
  print("String does not contain any vowels")

has= any(char in vowels for char in string2)

if has:
  print("String contains vowels")
else:
  print("String does not contain any vowels")

has= any(char in vowels for char in string3)

if has:
  print("String contains vowels")
else:
  print("String does not contain any vowels")

"""7. Write a program that allows to determine if a string is palindrome (a word or sentence that reads the same backward or forward). For example, 'never odd or even' or 'was it a car or a cat I saw' are palindrome strings."""

string ="never odd or even"

string = string.replace(" ", "")

if string == string[::-1]:
    print(f"{string1} is a palindrome")
else:
    print(f"{string1} is not a palindrome")

"""8. A capital of C euros at an interest of x percent per year for n years becomes C · (1 + x/100)^n euros. Design a Python program that, given a quantity C and the interest x, calculates the final capital only if x is a positive quantity."""

X= 100
n=25
C= 2500

if X>0:
  print(C*(1+X/100)**n)
else:
  print("Cannot define with negative numbers")

"""9. A courier company invoices its customers based on volume and weight according to the following rules:

  1. Regarding volume (v):
      - If v is less than or equal to 5 m3 -> €3;
      - If v is between 5 and 10 m3 -> €5;
      - If v is greater than 10 m3 -> €0.5 per m3.
  2. Regarding weight (pw
      - If w is less than or equal to 2 kg -> €1.7 per kg;
      - If w is greater than 2 kg -> €1.9 per kg.

 In any case, the company always chooses the billing option that produces the highest possible price. Write a program that using as input four variables of  package data (length, width, height, and weight) calculates the amount the customer must pay and print it. Consider a case in which the variables are not well written; for this case the program should print that there is an error, specifying in which one is the error.

 Example:
~~~
length (in meters): 2  
width(in meters): 2   
heigth(in meters): 2  
weight (in kgs): 2
The price of sending the package is 5€
~~~

"""

length =1
width =3
height =4
weight = 5

v= length*width*height
w=weight

if v <= 0:
  print("There was an error in the request. Please check your measurement indications")
  sys.exit()

if w<= 0:
  print("There was an error with your request. Please check your weight indications")
  sys.exit()

if v <=5:
  pricev = 3
elif v <10:
  pricev = 5
elif v>10:
  pricev = 0.5*w


if w <= 2:
  pricew = 1.7*w
else:
  pricew = 1.9*w


Total_price=pricew+pricev

print(f"{Total_price} is the total shipping price for your product")

"""10. Write a program in Python that given a numeric list, that counts all the occurrences of the different values in the list with their indices.
Example:
~~~
num_list=[1,2,5,9,2,1,5,9]  
The occurrences of value 1 in the list is: 2
The indices of value 1 in the list are: 0,5
The occurrences of value 2 in the list is: 2
The indices of value 2 in the list are: 1,4
The occurrences of value 5 in the list is: 2
The indices of value 5 in the list are: 2,6
The occurrences of value 9 in the list is: 2
The indices of value 9 in the list are: 3,7
~~~

"""

num_list=[1,2,5,9,2,1,5,9]

unique = set(num_list)

for index, num in enumerate(num_list):
  ocurrence = num_list.count(num)
  indice = str(index)
  print(f"The ocurrences of value {num} in the list is {ocurrence}")
  print(f"The indices of value {num} in the list is {indice}")
