# -*- coding: utf-8 -*-
"""Schrantz_Dante_04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zcCVdfwAWxy2-l8AaCQGl6RVnsZcM5kM

#Exercises using Dictionaries

**NOTE: Use the commands that we have seen in class up to now.**

1. Create a dictionary with car brands as keys and the owner country of each brand. Include at least three key-value pairs in your dictionary.
"""

car_brand = {
    'Range_Rover': 'United_Kingdom',
    'Lamborghini': 'Italy',
    'Tesla': 'United_States',
    'Hyundai': 'Korea'
    'GMC':'United_States'
}

"""2. Create a dictionary where the keys are the names of swimming style exercises, and the values are the number of laps you did in a session for freestyle, breaststroke, and backstroke:
- Use a for loop to print a series of messages like "I did 10 freestyle laps."
- Modify one of the values in your dictionary to represent doing more laps of a swimming style.
- Add a new key-value pair to your dictionary.
- Delete one of the key-value pairs from your dictionary.
"""

swimming = {
    'Breast_Stroke': 120,
    'frog': 120,
    'backstroke': 25
}

for style, laps in swimming.items():
    print("I did", laps, style, "laps.")

swimming['Breast_Stroke'] += 10

swimming['Butterfly'] = 13

del swimming['backstroke']

print(swimming)

"""3. List of countries by Human Development Index
- Wikipedia has a list of the countries ordered by HDI [list of countries](https://en.wikipedia.org/wiki/List_of_countries_by_Human_Development_Index). Choose 5 countries in the list.
    - Create a dictionary with names of the countries as keys, and the HDI as values.
    - Print only the names of the countries, using a loop.
    - Print only the HDIs of the countries, using a loop.
    - Print a series of messages like: "Switzerland has a HDI of 0.962".
"""

countries_hdi = {
    'France': 0.903,
    'Spain': 0.905,
    'Japan': 0.925,
    'Germany': 0.939,
    'Italy': 0.895
}

print("Names of countries:")
for country in countries_hdi.keys():
    print(country)

print("\nHDI of countries:")
for hdi in countries_hdi.values():
    print(hdi)

for country, hdi in countries_hdi.items():
    print(country, "has a HDI of", hdi)

"""4. Write a program that prompts the user to enter a sentence via keyboard input and generates a dictionary with the count of occurrences of each word in the sentence.
For example, if it receives "What a lovely day it is today" it should return:

- 'what': 1, 'a': 1, 'lovely': 1, 'day': 1, 'it': 1, 'is': 1, 'today': 1
"""

sentence = input("Enter a sentence: ")

dic = {}
for word in sentence.split():
    dic[word.lower()] = dic.get(word.lower(), 0) + 1

print(dic)

"""5. Write a program that prompts the user to enter a word via keyboard input and generates a dictionary with the count of occurrences of each character in the word. For example, if it receives "pamplona" it should return:
For example, if it gets "peace", it should turn back:

      'p': 1, 'e': 2, 'a': 1, 'c': 1
"""

word = input("Enter a word: ")

characters = {}
for char in word:
    characters[char] = characters.get(char, 0) + 1
print(characters)

"""6. This is an extension of exercise 3.
    - Create a new dictionary, where the keys area the names of 10 different countries you choose. This time, however, the values of the dictionary should be a list of the HDI and its ranking (the first country will be the one with the highest HDI): {'Switzerland': [0.962, 1]}
    - Print only the names of the countries, using a loop.
    - Print the HDIs of the countries, using the values of the dictionary and getting the first number of the list.
    - Print only the ranking of each country in the list, looping through the values of the dictionary and getting the second value of the list.
    - Print some sentences like: "Switzerland has a HDI value of 0.962, and it is in position 1".
"""

countries_hdi_ranking = {

    'France': [0.903,28],
    'Spain': [0.905,27],
    'Japan': [0.925,19],
    'Germany': [0.939,4],
    'Italy': [0.895,30]

}

print("Names of countries:")
for country in countries_hdi_ranking.keys():
    print(country)

print("\nHDI of countries:")
for country, data in countries_hdi_ranking.items():
    print(country, ":", data[0])

print("\nRankings of countries:")
for country, data in countries_hdi_ranking.items():
    print(country, "is in position", data[1])

for country, data in countries_hdi_ranking.items():
    print(country, "has a HDI value of", data[0], "and it is in position", data[1])